export const travelPackages = [
  { id: 1, name: 'Roman Holiday', duration: '5 Days', price: '₹1,30,000', image: './assets/image_1.jpeg', destination: 'Italy', rating: 4.8 },
  { id: 2, name: 'Venice Waterways', duration: '4 Days', price: '₹1,45,000', image: './assets/image_2.jpeg', destination: 'Italy', rating: 4.9 },
  { id: 3, name: 'Tuscan Sun Adventure', duration: '7 Days', price: '₹1,80,000', image: './assets/image_3.jpeg', destination: 'Italy', rating: 4.7 },
  { id: 4, name: 'Amalfi Coast Dreams', duration: '6 Days', price: '₹2,10,000', image: './assets/image_4.jpeg', destination: 'Italy', rating: 5.0 },
  { id: 5, name: 'Parisian Romance', duration: '7 Days', price: '₹1,50,000', image: './assets/image_5.jpeg', destination: 'France', rating: 4.9 },
  { id: 6, name: 'French Riviera', duration: '6 Days', price: '₹1,90,000', image: './assets/image_6.jpeg', destination: 'France', rating: 4.8 },
  { id: 7, name: 'Wines of Bordeaux', duration: '5 Days', price: '₹1,75,000', image: './assets/image_7.jpeg', destination: 'France', rating: 4.7 },
  { id: 8, name: 'Historic Normandy', duration: '4 Days', price: '₹1,20,000', image: './assets/image_8.jpeg', destination: 'France', rating: 4.6 },
  { id: 9, name: 'Majestic Japan Tour', duration: '10 Days', price: '₹2,50,000', image: './assets/image_9.jpeg', destination: 'Japan', rating: 5.0 },
  { id: 10, name: 'Tokyo City Lights', duration: '5 Days', price: '₹1,80,000', image: './assets/image_10.jpeg', destination: 'Japan', rating: 4.8 },
  { id: 11, name: 'Kyoto Temples & Zen', duration: '6 Days', price: '₹2,00,000', image: './assets/image_11.jpeg', destination: 'Japan', rating: 4.9 },
  { id: 12, name: 'Hokkaido Winter Fest', duration: '7 Days', price: '₹2,20,000', image: './assets/image_12.jpeg', destination: 'Japan', rating: 4.7 },
  { id: 13, name: 'New York Adventure', duration: '6 Days', price: '₹1,80,000', image: './assets/image_13.jpeg', destination: 'USA', rating: 4.8 },
  { id: 14, name: 'California Coastin\'', duration: '8 Days', price: '₹2,10,000', image: './assets/image_14.jpeg', destination: 'USA', rating: 4.6 },
  { id: 15, name: 'Grand Canyon Wonders', duration: '4 Days', price: '₹1,50,000', image: './assets/image_15.jpeg', destination: 'USA', rating: 4.9 },
  { id: 16, name: 'Alaskan Cruise', duration: '7 Days', price: '₹2,40,000', image: './assets/image_16.jpeg', destination: 'USA', rating: 4.7 },
  { id: 17, name: 'Swiss Alps Expedition', duration: '8 Days', price: '₹2,10,000', image: './assets/image_17.jpeg', destination: 'Switzerland', rating: 5.0 },
  { id: 18, name: 'Lakes of Interlaken', duration: '5 Days', price: '₹1,90,000', image: './assets/image_18.jpeg', destination: 'Switzerland', rating: 4.9 },
  { id: 19, name: 'Zurich & Lucerne', duration: '6 Days', price: '₹1,95,000', image: './assets/image_19.jpeg', destination: 'Switzerland', rating: 4.8 },
  { id: 20, name: 'Matterhorn Views', duration: '4 Days', price: '₹2,25,000', image: './assets/image_20.jpeg', destination: 'Switzerland', rating: 4.9 },
  { id: 21, name: 'Ancient Greek Odyssey', duration: '10 Days', price: '₹2,40,000', image: './assets/image_21.jpeg', destination: 'Greece', rating: 4.8 },
  { id: 22, name: 'Santorini Sunset', duration: '5 Days', price: '₹1,80,000', image: './assets/image_22.jpeg', destination: 'Greece', rating: 5.0 },
  { id: 23, name: 'Secrets of Peru', duration: '8 Days', price: '₹2,00,000', image: './assets/image_23.jpeg', destination: 'Peru', rating: 4.7 },
  { id: 24, name: 'Machu Picchu Trek', duration: '6 Days', price: '₹2,20,000', image: './assets/image_24.jpeg', destination: 'Peru', rating: 4.9 },
  { id: 25, name: 'Heart of Africa Safari', duration: '10 Days', price: '₹3,00,000', image: './assets/image_25.jpeg', destination: 'Kenya', rating: 4.8 },
  { id: 26, name: 'Masai Mara Adventure', duration: '7 Days', price: '₹2,80,000', image: './assets/image_26.jpeg', destination: 'Kenya', rating: 4.9 },
  { id: 27, name: 'Thai Beaches & Temples', duration: '9 Days', price: '₹95,000', image: './assets/image_27.jpeg', destination: 'Thailand', rating: 4.7 },
  { id: 28, name: 'Bangkok Street Food', duration: '4 Days', price: '₹75,000', image: './assets/image_28.jpeg', destination: 'Thailand', rating: 4.8 },
  { id: 29, name: 'Phuket Relaxation', duration: '6 Days', price: '₹85,000', image: './assets/image_29.jpeg', destination: 'Thailand', rating: 4.6 },
  { id: 30, name: 'London Calling', duration: '4 Days', price: '₹1,10,000', image: './assets/image_30.jpeg', destination: 'UK', rating: 4.7 },
  { id: 31, name: 'Scottish Highlands', duration: '7 Days', price: '₹1,60,000', image: './assets/image_31.jpeg', destination: 'UK', rating: 4.9 },
  { id: 32, name: 'Vibrant Rio Carnival', duration: '7 Days', price: '₹1,90,000', image: './assets/image_32.jpeg', destination: 'Brazil', rating: 4.8 },
  { id: 33, name: 'Amazon Rainforest', duration: '9 Days', price: '₹2,50,000', image: './assets/image_33.jpeg', destination: 'Brazil', rating: 4.7 },
  { id: 34, name: 'Canadian Rockies', duration: '8 Days', price: '₹2,20,000', image: './assets/image_34.jpeg', destination: 'Canada', rating: 4.9 },
  { id: 35, name: 'Toronto & Niagara', duration: '5 Days', price: '₹1,70,000', image: './assets/image_35.jpeg', destination: 'Canada', rating: 4.6 },
  { id: 36, name: 'Australian Outback', duration: '9 Days', price: '₹2,30,000', image: './assets/image_36.jpeg', destination: 'Australia', rating: 4.8 },
  { id: 37, name: 'Sydney Opera House', duration: '4 Days', price: '₹1,60,000', image: './assets/image_37.jpeg', destination: 'Australia', rating: 4.7 },
  { id: 38, name: 'Great Barrier Reef', duration: '7 Days', price: '₹2,60,000', image: './assets/image_38.jpeg', destination: 'Australia', rating: 4.9 },
  { id: 39, name: 'Viking Fjords of Norway', duration: '8 Days', price: '₹2,40,000', image: './assets/image_39.jpeg', destination: 'Norway', rating: 4.8 },
  { id: 40, name: 'Northern Lights Chase', duration: '6 Days', price: '₹2,70,000', image: './assets/image_40.jpeg', destination: 'Norway', rating: 5.0 },
];